### ISSUE TITLE
como ajudar guiadevopsbrasil

### ISSUE THREAD

**Issue by Fabiokleis** [waltenne/guiadevopsbrasil#9]
Opa, abri essa issue pois quero saber como posso ajudar com o guiadevopsbrasil, vi alguns diretorios com uns arquivos .md
Como posso contribuir ?

**Comment by waltenne** [comment]
Opa! boa tarde!

Peço desculpas pela demora no retorno @Fabiokleis, como vai?

Trabalhei hoje na parte da manhã melhorando o README.MD do projeto e deixando algumas orientações sobre sua pergunta e dando algumas dicas, poderia por favor validar se ficou claro e objetivo?

Lembrando que caso já tenha feito o fork oriento atualizar o projeto do repostório antes de fazer qualquer alteração, para pegar os ultimos commits

Caso o README.MD está Ok me avisa para que eu possa fechar essa issue.

**Comment by Fabiokleis** [comment]
Ok vlws!!

**Comment by waltenne** [comment]
@Fabiokleis tudo certo? Posso fechar a issue?

**Comment by Fabiokleis** [comment]
> @Fabiokleis tudo certo? Posso fechar a issue?

pode sim!
